source 'https://rubygems.org'

ruby '2.2.0'

gem 'rspec'
gem 'rake'
gem 'guard'
gem 'guard-rspec'
gem 'rb-readline'
gem 'sinatra', "1.4.7"
gem 'rack-test'
gem 'sinatra-contrib'
gem 'json'
gem 'mail'
gem 'tlsmail', '~> 0.0.1' if RUBY_VERSION <= '1.8.6'

group :test do
	gem 'rack-test'
end